package com.example.Google_Selenium2;

// Generated by Selenium IDE

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.firefox.FirefoxOptions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.util.HashMap;
import java.util.Map;



public class Robobar1Test {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @BeforeEach
    public void setUp() {
        FirefoxOptions options = new FirefoxOptions();
        options.setHeadless(true);
        driver = new FirefoxDriver(options);
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @AfterEach
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void robobartest1() {
        // Test name: robobar-test1
        // Step # | name | target | value
        // 1 | open | / |
        driver.get("http://localhost:3000/");
        // 2 | click | css=.ng-scope:nth-child(1) > .ng-binding:nth-child(1) |
        WebElement indexLoad =  new WebDriverWait(driver, 5)
                .until(ExpectedConditions.elementToBeClickable(By.cssSelector(".ng-scope:nth-child(1) > .ng-binding:nth-child(1)")));;


        driver.findElement(By.cssSelector(".ng-scope:nth-child(1) > .ng-binding:nth-child(1)")).click();
        // 3 | click | css=.ng-scope:nth-child(1) > .ng-binding:nth-child(2) |
        driver.findElement(By.cssSelector(".ng-scope:nth-child(1) > .ng-binding:nth-child(2)")).click();
        // 4 | click | css=.ng-scope:nth-child(1) > td .input-group-append > .btn | add drink 1 button
        driver.findElement(By.cssSelector(".ng-scope:nth-child(1) > td .input-group-append > .btn")).click();
        // 5 | click | css=tr:nth-child(4) > .ng-binding |
        driver.findElement(By.cssSelector("tr:nth-child(4) > .ng-binding")).click();
        // 6 | click | css=.ng-scope:nth-child(2) > .ng-binding:nth-child(1) |
        driver.findElement(By.cssSelector(".ng-scope:nth-child(2) > .ng-binding:nth-child(1)")).click();
        // 7 | click | css=.ng-scope:nth-child(2) > .ng-binding:nth-child(2) |
        driver.findElement(By.cssSelector(".ng-scope:nth-child(2) > .ng-binding:nth-child(2)")).click();
        // 8 | click | css=.ng-scope:nth-child(2) > td .input-group-append > .btn | add drink 2 button
        driver.findElement(By.cssSelector(".ng-scope:nth-child(2) > td .input-group-append > .btn")).click();
        // 9 | click | css=tr:nth-child(4) > .ng-binding |
        driver.findElement(By.cssSelector("tr:nth-child(4) > .ng-binding")).click();
        // 10 | click | css=.ng-scope:nth-child(3) > .ng-binding:nth-child(1) |
        driver.findElement(By.cssSelector(".ng-scope:nth-child(3) > .ng-binding:nth-child(1)")).click();
        // 11 | click | css=.ng-scope:nth-child(3) > .ng-binding:nth-child(2) |
        driver.findElement(By.cssSelector(".ng-scope:nth-child(3) > .ng-binding:nth-child(2)")).click();
        // 12 | click | css=.ng-scope:nth-child(3) .input-group-append > .btn | add drink 3 button
        driver.findElement(By.cssSelector(".ng-scope:nth-child(3) .input-group-append > .btn")).click();
        // 13 | click | css=tr:nth-child(4) > .ng-binding |
        driver.findElement(By.cssSelector("tr:nth-child(4) > .ng-binding")).click();
        String priceReal = "€6.25";
        String priceFlag = driver.findElement(By.cssSelector("tr:nth-child(4) > .ng-binding")).getText();
        //comprobamos si en cada bebida hay un elemento para comprobar precio total de 1 bebida de cada
        //comprobar si hay una bebida de cada
        String drink1 = driver.findElement(By.cssSelector(".ng-scope:nth-child(1) > td .form-control")).getText();
        String drink2 = driver.findElement(By.cssSelector(".ng-scope:nth-child(2) > td .form-control")).getText();
        String drink3 = driver.findElement(By.cssSelector(".ng-scope:nth-child(3) > td .form-control")).getText();

        if(drink1.equals("1") && drink2.equals("2") && drink3.equals("1")){
            //comparamos precios para ver si son iguales con ¡¡¡¡¡ 1 cantidad de cada bebida !!!!
            //si es cierto seguimos con la prueba
            if(priceReal == priceFlag){
                // 14 | click | css=.btn-success |
                driver.findElement(By.cssSelector(".btn-success")).click();
                // 15 | click | id=ageInput |

                WebElement ageLoad =  new WebDriverWait(driver, 5)
                        .until(ExpectedConditions.elementToBeClickable(By.id("ageInput")));
                // 16 | type | id=ageInput | 21
                driver.findElement(By.id("ageInput")).sendKeys("21");
                // 17 | click | css=.btn-success |
                driver.findElement(By.cssSelector(".btn-success")).click();
            }else{
                //si no es cierto mostramos un error en consola
                System.out.println("Precios por una bebida de cada no coinciden");
            }
        }else{
            //si no hay una bebida de cada, seguimos con la prueba normal
            System.out.println("prueba no realizada, ya que no hay 1 bebida de cada");
            // 14 | click | css=.btn-success |
            driver.findElement(By.cssSelector(".btn-success")).click();
            // 15 | click | id=ageInput |
            WebElement ageLoad =  new WebDriverWait(driver, 5)
                    .until(ExpectedConditions.elementToBeClickable(By.id("ageInput")));
            // 16 | type | id=ageInput | 21
            driver.findElement(By.id("ageInput")).sendKeys("21");
            // 17 | click | css=.btn-success |
            driver.findElement(By.cssSelector(".btn-success")).click();
        }


    }
}