package com.example.Google_Selenium2;
// Generated by Selenium IDE


import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.firefox.FirefoxOptions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.TimeUnit;


public class SearchImdbTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @BeforeEach
    public void setUp() {
        FirefoxOptions options = new FirefoxOptions();
        options.setHeadless(true);
        driver = new FirefoxDriver(options);
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @AfterEach
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void searchimdb() {
        // Test name: search-imdb
        // Step # | name | target | value
        // 1 | open | / |
        driver.get("https://www.imdb.com/");

        // 2 | setWindowSize | 858x859 |
        //driver.manage().window().setSize(new Dimension(858, 859));

        // 3 | type | id=suggestion-search | wandavision
        driver.manage().timeouts().implicitlyWait(3, TimeUnit.SECONDS);
        driver.findElement(By.id("suggestion-search")).sendKeys("wandavision");

        // 4 | sendKeys | id=suggestion-search | ${KEY_ENTER}
        //espera de 10 segundos a que cargue la pagina
        driver.manage().timeouts().implicitlyWait(3, TimeUnit.SECONDS);
        driver.findElement(By.id("suggestion-search")).sendKeys(Keys.ENTER);

        // 5 | click | linkText=WandaVision |


        //esperaimplicita de 10 segundos a que cargue la pagina
        //driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS); linkText=WandaVision
        WebElement WVWait = new WebDriverWait(driver, 5).until(ExpectedConditions.elementToBeClickable(By.linkText("WandaVision")));
        //driver.findElement(By.linkText("WandaVision")).click();

        // 6 | click | linkText=TRIVIA |
        driver.manage().timeouts().implicitlyWait(3, TimeUnit.SECONDS);
        driver.findElement(By.linkText("TRIVIA")).click();


    }
}