package com.example.Google_Selenium2;

// Generated by Selenium IDE
//esto es junit 4
//import org.junit.Test;
//import org.junit.Before;
//import org.junit.After;
//import static org.junit.Assert.*;


import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.firefox.FirefoxDriver;

import java.util.HashMap;
import java.util.Map;

public class SearchTestGoogle {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @BeforeEach
    public void setUp() {
        driver = new FirefoxDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @AfterEach
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void test2() {
        // Test name: test2
        // Step # | name | target | value
        // 1 | open | / |
        driver.get("https://www.google.es/");
        // 2 | setWindowSize | 858x855 |
        //driver.manage().window().setSize(new Dimension(858, 855));
        // 3 | selectFrame | index=0 |
        driver.switchTo().frame(0);
        // 4 | click | css=#introAgreeButton .RveJvd |
        driver.findElement(By.cssSelector("#introAgreeButton .RveJvd")).click();
        // 5 | selectFrame | relative=parent |
        driver.switchTo().defaultContent();
        // 6 | click | name=q |
        driver.findElement(By.name("q")).click();
        // 7 | type | name=q | devops
        driver.findElement(By.name("q")).sendKeys("devops");
        // 8 | sendKeys | name=q | ${KEY_ENTER}
        driver.findElement(By.name("q")).sendKeys(Keys.ENTER);
        // 9 | click | xpath=//div[@id='tads']/div/div/div/div/a/div |
        driver.findElement(By.cssSelector(".fdYsqf > .cfxYMc")).click();
    }
}
